minimumReleaseAgeExclude:
  - "@siyuan-community/siyuan-sdk@0.3.15 || 0.3.16 || 0.3.17"
shellEmulator: true

trustPolicy: no-downgrade

packages:
  - packages/*
  - plugins/*
  - tools/*
  - widgets/*
allowBuilds:
  esbuild: true
  svelte-preprocess: true
  unrs-resolver: false
