minimumReleaseAgeExclude:
  - "@siyuan-community/siyuan-sdk@0.3.17"
shellEmulator: true

trustPolicy: off

packages:
  - packages/*
  - plugins/*
  - tools/*
  - widgets/*
allowBuilds:
  esbuild: true
  svelte-preprocess: true
  unrs-resolver: false
